version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.client
    volumes:
      - ./client:/app
    ports:
      - "9000:9000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    volumes:
      - ./server:/app
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cheburgram
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cheburgram
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
