FROM node:18-alpine

RUN addgroup -S gadmin && adduser -S admin -G gadmin

WORKDIR /app

RUN npm install -g nodemon

RUN chmod -R 755 /app

RUN chown -R admin:gadmin /app

USER admin

EXPOSE 4000

CMD [ "sh", "-c", "while :; do sleep 1000; done" ]